cmake_minimum_required(VERSION 4.2)
project(LearnC__)

set(CMAKE_CXX_STANDARD 20)

add_executable(LearnC__ posicionesPunteros.cpp
        aritmeticaPunteros.cpp
        caracteresPunteros.cpp
        new.cpp
        nodos.cpp
        ejercicioPila.cpp
        colas.cpp
        ejercicioCola.cpp
        ejercicioColasBanco.cpp
        listasEnlasadas.cpp
        ejercicioSorteoCochera.cpp)
